services:
  www:
    build: .
    depends_on:
      db:
        condition: service_healthy
    tty: true
    volumes:
      - "./:/var/www" # sync local dir with container web dir
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=midair
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d" # sync MySQL data with container
    healthcheck:
      test: "mysql -uroot -proot midair -e 'select 1'"
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
